# 100 numpy exercises (Optional)

Source: https://github.com/rougier/numpy-100

Note: I have done this as a part of practice according to my understanding. If you feel, at some part any incorrectness, let me now I will be happy to correct it :)

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print('NumPy version is', np.version.version)
print('NumPy configuration is', np.show_config())

NumPy version is 1.24.1
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
# https://numpy.org/doc/stable/reference/generated/numpy.zeros.html
# https://docs.oracle.com/cd/E19957-01/805-4940/z400091044d0/index.html
np.zeros(10, dtype=np.float64)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
numpy_array = np.array([1,2,3,4,5])
print("Size of the array: ", numpy_array.size)
print("data type of numpy array:", numpy_array.dtype)
print("Memory size of one array element in bytes: ", numpy_array.itemsize)
print("Memory size of numpy array in bytes:", numpy_array.size * numpy_array.itemsize)

Size of the array:  5
data type of numpy array: int32
Memory size of one array element in bytes:  4
Memory size of numpy array in bytes: 20


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
python -c "import numpy; numpy.info(numpy.add)" # command applicable in terminal/command prompt

SyntaxError: invalid syntax (1749058911.py, line 1)

In [ ]:
np.info(np.add)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
numpy_array = np.zeros(10)
numpy_array[4] = 1
numpy_array

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
np.arange(10,50)

In [ ]:
np.linspace(10,49)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
numpy_array = np.arange(10)
numpy_array = numpy_array[::-1]
numpy_array

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
numpy_array = np.arange(9)
numpy_array.reshape(3,3)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
numpy_array = np.array([1,2,0,0,4,0])
nz_indices = np.array([], dtype=np.int32)
for i in range(len(numpy_array)):
    if numpy_array[i] != 0:
        nz_indices = np.append(nz_indices, i)
nz_indices

In [ ]:
nz_indices = np.nonzero(numpy_array)
nz_indices

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.identity(3)

In [ ]:
np.eye(3, k=0)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
# https://numpy.org/doc/stable/reference/random/index.html

numpy_array = np.random.rand(3,3,3)
numpy_array

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
numpy_array = np.random.randint(100, size=(10,10))
print(numpy_array)
print("Minimum of the array:", np.min(numpy_array))
print("Maximum of the array:", np.max(numpy_array))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
numpy_array = np.random.randint(100, size=30)
print(numpy_array)
print("Mean of the array:", np.mean(numpy_array))

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [6]:
k = int(input("Enter value of k for k x k structure 2D structure:"))

final_arr = []
for i in range(k):
    if i == 0 or i == k-1:
        new_array = np.ones(k)
        final_arr.append(list(new_array))
    else:
        new_array = np.zeros(k)
        new_array[0], new_array[k-1] = 1,1
        final_arr.append(list(new_array))
final_arr = np.array(final_arr)
final_arr

Enter value of k for k x k structure 2D structure: 4


array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [7]:
# source = http://sanjaymeena.io/tech/100-Numpy-Exercises/
Z = np.ones((6,6))
Z[1:-1,1:-1]=0
Z

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [8]:
numpy_array = np.arange(16).reshape(4,4)
a = numpy_array.shape[0]
zeros_border = np.zeros(a)
dummy = list(numpy_array)
dummy = [zeros_border] + dummy + [zeros_border]
numpy_array = np.array(dummy)
a = numpy_array.shape[0]
zeros_border = np.zeros(a)
numpy_array = np.concatenate((zeros_border.reshape(a,1), numpy_array), axis=1)
numpy_array = np.concatenate((numpy_array, zeros_border.reshape(a,1)), axis=1)
numpy_array

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  2.,  3.,  0.],
       [ 0.,  4.,  5.,  6.,  7.,  0.],
       [ 0.,  8.,  9., 10., 11.,  0.],
       [ 0., 12., 13., 14., 15.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [9]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [10]:
numpy_array = np.zeros(25).reshape(5,5)
dummy = 1
for i in range(numpy_array.shape[0]):
    for j in range(numpy_array.shape[1]):
        if i==j and i!=0:
            numpy_array[i][j-1] = dummy
            dummy += 1
numpy_array

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [11]:
numpy_array = np.zeros(64).reshape(8,8)
for i in range(len(numpy_array)):
    if i%2 == 0:
        numpy_array[i][1::2] = 1
    else:
        numpy_array[i][0::2] = 1
numpy_array

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [12]:
numpy_array = np.ones(6*7*8).reshape(6,7,8)
element_number = int(input("Enter the k_th element for which you want to know the index (starting from one):"))
index = [0,0,0]
for i in range(element_number):
    if (i%(numpy_array.shape[1] * numpy_array.shape[2]) == 0) and i!= 0:
        index[0] += 1
        index[1] = 0
        index[2] = 0
    elif (i%(numpy_array.shape[2]) == 0) and i!= 0:
        index[1] += 1
        index[2] = 0
    else:
        index[2] += 1
print("Index of the element counted from (0,0,0):", index)

Enter the k_th element for which you want to know the index (starting from one): 100


Index of the element counted from (0,0,0): [1, 5, 3]


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [13]:
pattern = np.array([[0,1],[1,0]])
numpy_array = np.tile(pattern, (4,4))
numpy_array

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [14]:
numpy_array = np.random.randint(100, size=(5,5))
print("Original array:\n", numpy_array)
norm_value = np.linalg.norm(numpy_array) # Frobenius norm
numpy_array = numpy_array/norm_value
print("Normalised array:\n", numpy_array)

Original array:
 [[33 78 83 35 32]
 [31 90 59 54 15]
 [74 90 40 88 92]
 [20 75 52 59 73]
 [66 96 17 85 49]]
Normalised array:
 [[0.10213048 0.24139932 0.25687363 0.10832021 0.09903562]
 [0.09594075 0.27853767 0.18259692 0.1671226  0.04642295]
 [0.22901986 0.27853767 0.12379452 0.27234795 0.2847274 ]
 [0.06189726 0.23211473 0.16093288 0.18259692 0.225925  ]
 [0.20426096 0.29710685 0.05261267 0.26306336 0.15164829]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [15]:
# https://numpy.org/doc/stable/reference/arrays.dtypes.html
# https://rgbacolorpicker.com/

custom_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
pink = np.array([(255, 0, 255, 255)], dtype=custom_dtype)
pink

array([(255, 0, 255, 255)],
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

In [16]:
wrong = pink = np.array([(256, 0, 255, 255)], dtype=custom_dtype)

C:\Users\vinay\AppData\Local\Temp\ipykernel_17488\1004347360.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  wrong = pink = np.array([(256, 0, 255, 255)], dtype=custom_dtype)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [17]:
numpy_array_1 = np.array([[1,2,3],
                          [4,5,6],
                          [7,8,9],
                          [10,11,12],
                          [13,14,15]])
numpy_array_2 = np.array([[1,2],
                          [4,5],
                          [7,8]])
first_mat_shape = numpy_array_1.shape
second_mat_shape = numpy_array_2.shape
final_mat = np.zeros(first_mat_shape[0]*second_mat_shape[1]).reshape(first_mat_shape[0],second_mat_shape[1])
for i in range(first_mat_shape[0]):
    for j in range(second_mat_shape[1]):
        final_mat[i][j] = (numpy_array_1[i] * numpy_array_2[:,j]).sum()
final_mat

array([[ 30.,  36.],
       [ 66.,  81.],
       [102., 126.],
       [138., 171.],
       [174., 216.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [18]:
numpy_array = np.random.randint(10, size=(10))
print(numpy_array)
numpy_array[3:9] = numpy_array[3:9]*-1
print(numpy_array)

[2 9 0 4 7 9 6 0 9 1]
[ 2  9  0 -4 -7 -9 -6  0 -9  1]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [19]:
print(sum(range(5),-1)) # sum(iterable, start)
from numpy import * # imports all functions and classes from numpy, makes code heavier if only one/two function are used from numpy
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [20]:
Z = 8
print(Z**Z)
print(2 << Z >> 2) # <<: left shift, >>:right shift
print(Z < -Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

16777216
128
False
8j
8.0
False


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [21]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\vinay\AppData\Local\Temp\ipykernel_17488\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\vinay\AppData\Local\Temp\ipykernel_17488\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\vinay\AppData\Local\Temp\ipykernel_17488\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [23]:
def round_away_from_zero_array(arr,y):
    return np.round(arr,y)

test = np.array([32.11, 51.5, 0.112])
print(round_away_from_zero_array(test,0))

[32. 52.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [24]:
numpy_array_1 = np.array([1,4,7,3,9,0])
numpy_array_2 = np.array([2,9,10,11,4])
common_values = np.array([], dtype = np.int64)
for i in numpy_array_1:
    if i in numpy_array_2:
        common_values = np.append(common_values, i)
common_values

array([4, 9], dtype=int64)

In [25]:
print(np.intersect1d(numpy_array_1, numpy_array_2))

[4 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [26]:
np.seterr(all="ignore")
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [27]:
print(np.sqrt(-1), np.emath.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan 1j
False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [28]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2023-02-02 2023-02-03 2023-02-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [29]:
print(np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [30]:
print(np.arange('2010-01-01', '2015-01-01', dtype='datetime64[Y]'))
print(np.arange('2016-01-01', '2017-01-01', dtype='datetime64[M]'))
print(np.arange('2016-01-01', '2016-01-02', dtype='datetime64[h]'))

['2010' '2011' '2012' '2013' '2014']
['2016-01' '2016-02' '2016-03' '2016-04' '2016-05' '2016-06' '2016-07'
 '2016-08' '2016-09' '2016-10' '2016-11' '2016-12']
['2016-01-01T00' '2016-01-01T01' '2016-01-01T02' '2016-01-01T03'
 '2016-01-01T04' '2016-01-01T05' '2016-01-01T06' '2016-01-01T07'
 '2016-01-01T08' '2016-01-01T09' '2016-01-01T10' '2016-01-01T11'
 '2016-01-01T12' '2016-01-01T13' '2016-01-01T14' '2016-01-01T15'
 '2016-01-01T16' '2016-01-01T17' '2016-01-01T18' '2016-01-01T19'
 '2016-01-01T20' '2016-01-01T21' '2016-01-01T22' '2016-01-01T23']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [31]:
A = np.ones(3) * 1
B = np.ones(3) * 2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.multiply(A, -1, out=A)
np.multiply(B, A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [32]:
random_array = np.random.uniform(low=0, high=10, size=50)

print(random_array)

# method 1: only integer value associated with a number
int_random_array = np.array([], dtype=np.int64)
for i in random_array:
    int_random_array = np.append(int_random_array, int(i))
print(int_random_array)

# method 2: closest integer value greater than a number
int_random_array = np.array([], dtype=np.int64)
for i in random_array:
    int_random_array = np.append(int_random_array, int(np.ceil(i)))
print(int_random_array)

# method 3: closest integer value less than a number
int_random_array = np.array([], dtype=np.int64)
for i in random_array:
    int_random_array = np.append(int_random_array, int(np.floor(i)))
print(int_random_array)

# method 4: closest integer value
int_random_array = np.array([], dtype=np.int64)
for i in random_array:
    int_random_array = np.append(int_random_array, int(np.around(i)))
print(int_random_array)

# method 5: only integer value associated with a number
int_random_array = np.array([], dtype=np.int64)
for i in random_array:
    int_random_array = np.append(int_random_array, int(np.trunc(i)))
print(int_random_array)

[0.82975192 2.59276835 4.02950847 3.73018545 4.3239443  9.85527762
 1.48940035 5.47752303 4.15612036 3.08115582 0.61662628 1.71276621
 8.52610074 1.43984243 2.63104939 0.93876674 9.3065617  5.96939839
 3.19974407 3.25195603 2.93013944 3.05296757 7.8362284  9.71318432
 9.02498662 1.22283535 2.71517404 6.19028978 2.72693562 0.63952056
 2.97207361 6.67185537 3.24753454 1.61793472 0.43152064 4.40336255
 1.8335839  6.54970829 4.2869573  1.19080199 8.57779695 3.66930973
 1.66964817 4.17346817 2.93531919 9.68309483 8.8672532  1.74491513
 4.21034183 7.84575128]
[0 2 4 3 4 9 1 5 4 3 0 1 8 1 2 0 9 5 3 3 2 3 7 9 9 1 2 6 2 0 2 6 3 1 0 4 1
 6 4 1 8 3 1 4 2 9 8 1 4 7]
[ 1  3  5  4  5 10  2  6  5  4  1  2  9  2  3  1 10  6  4  4  3  4  8 10
 10  2  3  7  3  1  3  7  4  2  1  5  2  7  5  2  9  4  2  5  3 10  9  2
  5  8]
[0 2 4 3 4 9 1 5 4 3 0 1 8 1 2 0 9 5 3 3 2 3 7 9 9 1 2 6 2 0 2 6 3 1 0 4 1
 6 4 1 8 3 1 4 2 9 8 1 4 7]
[ 1  3  4  4  4 10  1  5  4  3  1  2  9  1  3  1  9  6  3  3  3  3  8 10
  9  1 

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [33]:
pattern = np.arange(0,5,1)
numpy_array = np.tile(pattern, (5,1))
numpy_array

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [34]:
# Ref: https://github.com/zuoxiang95/Learning-DeepLearning/blob/master/numpy_exercise/numpy_100.py
x = np.zeros((5, 5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [35]:
def generate_integers():
    for i in range(10):
        yield i
result = generate_integers()
print(result)
print(np.asarray(list(result), dtype=np.int32))
print("result set accessible only once, therefore empty", np.asarray(list(result), dtype=np.int32))
for i in result:
    print(i)

<generator object generate_integers at 0x000001BE1FD135F0>
[0 1 2 3 4 5 6 7 8 9]
result set accessible only once, therefore empty []


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [36]:
''' 
Basic trick for manual calculation,
we need 10 numbers excluding 0 and 1, means 12 numbers if 0 and 1 are included.
Therefore by 11 gaps between 12 numbers we get 10 numbers, 1/11 = 0.0909.
0, 0+1/11, 0+2/11, 0+3/11, ... , 0+10/11, 1.
By this we can exclude 1st and last element.
'''
np.linspace(0,1,12,endpoint=True)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [37]:
random_array = np.random.uniform(low=0, high=10, size=10)
print("Original array: ", random_array)
print("Sorted array:", sorted(random_array))

Original array:  [2.4465218  5.05625382 2.2742737  4.9351645  8.98771936 6.98988971
 0.96276574 7.06586413 9.14244367 4.79780995]
Sorted array: [0.9627657424036473, 2.274273704480877, 2.4465217971857767, 4.7978099450407825, 4.935164496850622, 5.056253820197368, 6.989889707835316, 7.065864127431815, 8.987719364107493, 9.14244367155496]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [38]:
import timeit

In [39]:
code_segment = '''\
import numpy as np
array = np.arange(0,10,1)
np.sum(array)
'''

# define the code statement to test and calculate the execution time
exec_time = timeit.timeit(code_segment, number = 1000)

# printing the execution time in seconds
print(exec_time, "secs.")

0.007425600000004806 secs.


In [40]:
code_segment = '''\
import numpy as np
array = np.arange(0,10,1)
sum = 0
for i in array:
    sum += i
'''

# define the code statement to test and calculate the execution time
exec_time = timeit.timeit(code_segment, number = 1000)

# printing the execution time in seconds
print(exec_time, "secs.")

0.0031135000000119817 secs.


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [41]:
A = np.array([1,2,3,4])
B = np.array([1,2,3,3])
print(A == B)
print(np.array_equal(A, B))

A = np.array([1,2,3,4])
B = np.array([1,2,3,4])
print(A == B)
print(np.array_equal(A, B))

[ True  True  True False]
False
[ True  True  True  True]
True


#### 43. Make an array immutable (read-only) (★★☆)

In [42]:
A = np.ones(5)
print(A)
A[0] = 3
print(A)
A.setflags(write=False)
A[1] = 5
print(A)

[1. 1. 1. 1. 1.]
[3. 1. 1. 1. 1.]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [43]:
cartesian_coordinates = np.random.randint(1, 10, size=(10,2))
print("Cartesian coordinates", cartesian_coordinates)
polar_coordinates = np.zeros_like(cartesian_coordinates, dtype = np.float64)
for i in range(len(cartesian_coordinates)):
    r = np.sqrt(np.sum(cartesian_coordinates[i]**2))
    theta = np.arctan(cartesian_coordinates[i][0]/cartesian_coordinates[i][1])
    polar_coordinates[i] = (r, theta)
print("Its corresponding polar coordinates", polar_coordinates)

Cartesian coordinates [[5 9]
 [2 3]
 [9 8]
 [9 4]
 [1 1]
 [6 7]
 [7 2]
 [2 2]
 [1 4]
 [4 6]]
Its corresponding polar coordinates [[10.29563014  0.5070985 ]
 [ 3.60555128  0.5880026 ]
 [12.04159458  0.84415399]
 [ 9.8488578   1.152572  ]
 [ 1.41421356  0.78539816]
 [ 9.21954446  0.70862627]
 [ 7.28010989  1.29249667]
 [ 2.82842712  0.78539816]
 [ 4.12310563  0.24497866]
 [ 7.21110255  0.5880026 ]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [44]:
numpy_array = np.random.randint(10, size = (10))
print("Original array: ", numpy_array)
index = numpy_array.argmax() # Since it only returns the first maximum value index
numpy_array[index] = 0
print("array after replacing maximum value with 0: ", numpy_array)

Original array:  [6 5 9 4 5 8 4 8 0 5]
array after replacing maximum value with 0:  [6 5 0 4 5 8 4 8 0 5]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [45]:
structured_array = np.zeros((5, 5), [('x', np.float64), ('y', np.float64)])
structured_array['x'], structured_array['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
structured_array

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [46]:
X = np.random.randint(10, size=(3))
print(X)
Y = np.random.randint(10, size=(5))
print(Y)
C = np.zeros((len(X), len(Y)))
for i in range(len(C)):
    for j in range(len(C[0])):
        C[i][j] = 1/(X[i] - Y[j])
print(C)

[3 4 7]
[9 7 0 0 4]
[[-0.16666667 -0.25        0.33333333  0.33333333 -1.        ]
 [-0.2        -0.33333333  0.25        0.25               inf]
 [-0.5                inf  0.14285714  0.14285714  0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [47]:
# Ref: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_hints_with_solutions.md
for datatype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(datatype).min)
   print(np.iinfo(datatype).max)

for datatype in [np.float32, np.float64]:
   print(np.finfo(datatype).min)
   print(np.finfo(datatype).max)
   print(np.finfo(datatype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [48]:
np.set_printoptions(threshold=float("inf"))
numpy_array = np.zeros((40,40))
print(numpy_array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [49]:
vector = np.arange(50, 100, 3)
print(vector)
scalar = np.random.randint(50,100)
print(scalar)
index = (np.abs(vector-scalar)).argmin()
print(vector[index])

[50 53 56 59 62 65 68 71 74 77 80 83 86 89 92 95 98]
66
65


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [50]:
structured_array = np.zeros((4, 4, 1), [ ('position', [('x', np.float64), ('y', np.float64)]), ('color', [('r', np.int16), ('g', np.int16), ('b', np.int16)])])
structured_array['position']['x'], structured_array['position']['y'], structured_array['color'] = np.meshgrid(np.linspace(0, 3, 4, endpoint=True), np.linspace(0, 3, 4, endpoint=True), np.random.randint(low=0, high=255, size=(1)))
print(structured_array)

[[[((0., 0.), (198, 198, 198))]
  [((1., 0.), (198, 198, 198))]
  [((2., 0.), (198, 198, 198))]
  [((3., 0.), (198, 198, 198))]]

 [[((0., 1.), (198, 198, 198))]
  [((1., 1.), (198, 198, 198))]
  [((2., 1.), (198, 198, 198))]
  [((3., 1.), (198, 198, 198))]]

 [[((0., 2.), (198, 198, 198))]
  [((1., 2.), (198, 198, 198))]
  [((2., 2.), (198, 198, 198))]
  [((3., 2.), (198, 198, 198))]]

 [[((0., 3.), (198, 198, 198))]
  [((1., 3.), (198, 198, 198))]
  [((2., 3.), (198, 198, 198))]
  [((3., 3.), (198, 198, 198))]]]


In [51]:
np.random.randint(low=0, high=255, size=(1))

array([60])

In [52]:
Z = np.zeros(10, [('position', [('x', float), ('y', float)]), ('color', [('r', float), ('g', float), ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [53]:
np.set_printoptions(threshold=6)
x_y_coordinates = np.random.randint(100, size=(100,2))
print(x_y_coordinates)
x_coordinates, y_coordinates = x_y_coordinates[:,0], x_y_coordinates[:,1]
x_coordinates = x_coordinates.reshape(x_coordinates.shape[0],1)
y_coordinates = y_coordinates.reshape(y_coordinates.shape[0],1)
distance_matrix = np.sqrt(np.square(x_coordinates-x_coordinates.T) + np.square(y_coordinates-y_coordinates.T))
distance_matrix

[[55  0]
 [80 48]
 [79 40]
 ...
 [66 12]
 [69 32]
 [74 56]]


array([[ 0.        , 54.12023651, 46.64761516, ..., 16.2788206 ,
        34.92849839, 59.13543777],
       [54.12023651,  0.        ,  8.06225775, ..., 38.62641583,
        19.41648784, 10.        ],
       [46.64761516,  8.06225775,  0.        , ..., 30.87069808,
        12.80624847, 16.76305461],
       ...,
       [16.2788206 , 38.62641583, 30.87069808, ...,  0.        ,
        20.22374842, 44.72135955],
       [34.92849839, 19.41648784, 12.80624847, ..., 20.22374842,
         0.        , 24.51530134],
       [59.13543777, 10.        , 16.76305461, ..., 44.72135955,
        24.51530134,  0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [54]:
numpy_float_array = np.random.rand(10).astype(np.float32)
print(numpy_float_array, numpy_float_array.dtype)
numpy_integer_array = numpy_float_array.astype('i')
print(numpy_integer_array, numpy_integer_array.dtype)

[0.5780966  0.9293439  0.5035396  ... 0.30106473 0.9892366  0.3045566 ] float32
[0 0 0 ... 0 0 0] int32


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [55]:
# To read this file into a numpy array, we can use the genfromtxt function.
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", missing_values=' ', filling_values=0, dtype=np.int8)
print(Z)

[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [56]:
numpy_array = np.array(['apple', 'banana', 'cherry', 'guava', 'jackfruit', 'mango', 'orange', 'papaya', 'sitafal'])
for index, i in np.ndenumerate(numpy_array):
    print(index, i)

(0,) apple
(1,) banana
(2,) cherry
(3,) guava
(4,) jackfruit
(5,) mango
(6,) orange
(7,) papaya
(8,) sitafal


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [57]:
import sys
np.set_printoptions(threshold=sys.maxsize)
mean = (1, 2)
cov = [[1, 0], [0, 1]]
np.random.multivariate_normal(mean, cov, 100)

array([[ 0.74952353,  2.01363149],
       [ 0.95405444,  2.65100123],
       [ 0.99191206,  2.49869753],
       [-0.71499304,  0.9917297 ],
       [ 1.76828321,  2.315716  ],
       [ 1.75676912,  2.2728857 ],
       [-1.50163281,  2.43789928],
       [ 1.2680285 ,  0.43063725],
       [ 2.32434015,  2.21756814],
       [ 0.14974271,  0.14369955],
       [ 1.60506509,  2.16387543],
       [-0.79287776,  0.55365258],
       [ 1.45901245,  1.80887507],
       [ 0.69125255,  1.98431262],
       [ 2.02847351,  3.13209944],
       [ 1.93363604,  1.11986883],
       [ 0.91552806,  1.94915585],
       [ 0.20773657,  3.67248174],
       [-0.8493481 ,  1.85171804],
       [-0.26869751,  1.19641988],
       [-0.77093092,  1.20570355],
       [ 2.30863297,  3.1138    ],
       [ 1.66279753,  0.11436574],
       [ 1.09019181,  3.43566712],
       [ 1.61828149,  1.99758399],
       [ 0.31786815,  1.37576237],
       [ 1.58712239,  2.17366198],
       [ 1.33474007,  1.7173404 ],
       [-0.83993438,

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [58]:
numpy_array = np.zeros((10,10), dtype = np.int32)
print("Original array:", numpy_array)
p = int(input('How much value you want to replace:'))
indexes = []
for i in range(p):
    indexes.append(np.random.randint(numpy_array.shape[0], size=(numpy_array.ndim)))
print("Indexes where 0 will be replaced:", indexes)
new_elements = []
for index in indexes:
    element = np.random.randint(10)
    new_elements.append(element)
    numpy_array[index[0]][index[1]] = element
print("New elements:", new_elements)
print("Modified array:", numpy_array)

Original array: [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


How much value you want to replace: 20


Indexes where 0 will be replaced: [array([0, 4]), array([9, 9]), array([4, 4]), array([4, 2]), array([3, 8]), array([0, 9]), array([7, 7]), array([7, 4]), array([0, 5]), array([4, 8]), array([7, 0]), array([8, 1]), array([2, 3]), array([1, 6]), array([1, 4]), array([3, 6]), array([5, 3]), array([0, 7]), array([6, 9]), array([5, 0])]
New elements: [7, 5, 4, 6, 6, 9, 1, 5, 8, 8, 3, 2, 8, 7, 7, 4, 1, 8, 9, 5]
Modified array: [[0 0 0 0 7 8 0 8 0 9]
 [0 0 0 0 7 0 7 0 0 0]
 [0 0 0 8 0 0 0 0 0 0]
 [0 0 0 0 0 0 4 0 6 0]
 [0 0 6 0 4 0 0 0 8 0]
 [5 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 9]
 [3 0 0 0 5 0 0 1 0 0]
 [0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 5]]


In [59]:
indexes[0], indexes[0][0]

(array([0, 4]), 0)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [60]:
Matrix = np.random.randint(100, size=(5,5))
print("Original matrix:", Matrix)
for i in range(len(Matrix)):
    row_mean = np.mean(Matrix[i])
    for j in range(len(Matrix[i])):
        Matrix[i][j] -= row_mean
print("Modified matrix with element contain only integer value associated with a number:", Matrix)

Original matrix: [[96 70 16 83 39]
 [49 25 62 94 53]
 [19  0 37 93  7]
 [93 72  8 82 96]
 [ 8 13 62 29 27]]
Modified matrix with element contain only integer value associated with a number: [[ 35   9 -44  22 -21]
 [ -7 -31   5  37  -3]
 [-12 -31   5  61 -24]
 [ 22   1 -62  11  25]
 [-19 -14  34   1   0]]


#### 59. How to sort an array by the nth column? (★★☆)

In [61]:
n = 2 # column number along which array need to be sorted
Matrix[Matrix[:, n].argsort()]

array([[ 22,   1, -62,  11,  25],
       [ 35,   9, -44,  22, -21],
       [ -7, -31,   5,  37,  -3],
       [-12, -31,   5,  61, -24],
       [-19, -14,  34,   1,   0]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [62]:
for i in range(len(Matrix[0])):
    if np.sum(Matrix[:, i]) == 0:
        print("a null column:", i)
    else:
        print("Not a null column:", i)

Not a null column: 0
Not a null column: 1
Not a null column: 2
Not a null column: 3
Not a null column: 4


#### 61. Find the nearest value from a given value in an array (★★☆)

In [63]:
vector = np.arange(50, 100, 3)
print(vector)
scalar = np.random.randint(50,100)
print(scalar)
index = (np.abs(vector-scalar)).argmin()
print(vector[index])

[50 53 56 59 62 65 68 71 74 77 80 83 86 89 92 95 98]
90
89


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [64]:
numpy_array_1 = np.linspace(0,2,3).reshape(1,3)
numpy_array_2 = np.linspace(0,2,3).reshape(3,1)
sum = 0
for i, j in zip(np.nditer(numpy_array_1), np.nditer(numpy_array_2)):
    sum += (i + j)
sum

6.0

#### 63. Create an array class that has a name attribute (★★☆)

In [65]:
class array_class:
    def __init__(self, array, name):
        self.numpy_array = array
        self.array_name = name
    def printname(self):
        print('The name of the array is "', self.array_name, '" and the array is', self.numpy_array)

array = array_class(np.arange(0,10,1), "10_numbers")
array.printname()

The name of the array is " 10_numbers " and the array is [0 1 2 3 4 5 6 7 8 9]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [66]:
numpy_array = np.random.randint(0, 100, size=(10))
print(numpy_array)
second_vector = np.random.randint(0, numpy_array.shape[0], size = numpy_array.shape[0]-5)
print(second_vector)
second_vector_unique = np.unique(second_vector)
print(second_vector_unique)
for i in second_vector_unique:
    numpy_array[i] += 1
print(numpy_array)

[55 59  7 32 91 63 37 34 40 17]
[5 8 8 9 2]
[2 5 8 9]
[55 59  8 32 91 64 37 34 41 18]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [67]:
X = np.random.randint(0, 100, size=(10))
print(X)
I = np.random.randint(0, numpy_array.shape[0], size = numpy_array.shape[0]-5)
print(I)
I_unique = np.unique(I)
print(I_unique)
F = np.array([], dtype=np.int32)
for i in I_unique:
    F = np.append(F, X[i])
print(F)

[70 70 68 70 45 50 93 83 36 77]
[8 1 4 0 0]
[0 1 4 8]
[70 70 45 36]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [68]:
np.set_printoptions(threshold=6)
h, w = 10, 10
image = np.random.randint(0, high=255, size=(h,w,3), dtype=np.ubyte) #UByte is an 8-bit unsigned integral data type, with values ranging from 0 to 255, inclusive
print(image)
colors = np.unique(image.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

[[[ 32 117 201]
  [ 87  64  97]
  [208  64 148]
  ...
  [ 73 221 228]
  [ 40 164  88]
  [ 74  38  79]]

 [[140  88  26]
  [238  14 159]
  [182  14 240]
  ...
  [119 174  45]
  [186 136 103]
  [ 40  59  89]]

 [[ 70 177  35]
  [  9 243 232]
  [ 39 224 101]
  ...
  [170 242 254]
  [ 41 239  11]
  [ 14  86  41]]

 ...

 [[183 135 239]
  [ 72  82 138]
  [233 206 138]
  ...
  [ 58 127  53]
  [ 80 248 188]
  [138 131 248]]

 [[  8 191 129]
  [153  48  41]
  [143 103 125]
  ...
  [ 57 184  46]
  [128  69  82]
  [232 167  12]]

 [[ 18 118  44]
  [  8  80 193]
  [194   0  43]
  ...
  [141  57 153]
  [103 128  43]
  [166  43  64]]]
100


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [69]:
numpy_array = np.random.randint(0,5, size=(2,2,2,2))
print("Original array:\n", numpy_array)
print("Array after sum over the last two axis at once:\n", np.sum(numpy_array, axis=(-2,-1)))

Original array:
 [[[[3 3]
   [1 3]]

  [[0 2]
   [2 2]]]


 [[[0 3]
   [2 4]]

  [[3 0]
   [0 3]]]]
Array after sum over the last two axis at once:
 [[10  6]
 [ 9  6]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [70]:
np.set_printoptions(threshold=float('inf'))
numpy_array = np.random.randint(0,10, size=10)
print("Original array:\n", numpy_array)
subset_indices = np.random.randint(0,numpy_array.shape[0], size=(numpy_array.shape[0], np.random.randint(0,10)))
print("Subset indices over which mean to be taken from D:", subset_indices)
new_array = np.array([])
for subset_index in subset_indices:
    new_array = np.append(new_array, np.mean(np.array(numpy_array)[np.unique(subset_index)]))
print("New array consisting of mean of elements", new_array)

Original array:
 [9 1 9 5 1 9 8 3 1 4]
Subset indices over which mean to be taken from D: [[2 5 4]
 [4 1 6]
 [0 8 1]
 [1 0 9]
 [0 8 5]
 [0 8 4]
 [8 5 2]
 [9 3 5]
 [0 7 5]
 [0 1 5]]
New array consisting of mean of elements [6.33333333 3.33333333 3.66666667 4.66666667 6.33333333 3.66666667
 6.33333333 6.         7.         6.33333333]


#### 69. How to get the diagonal of a dot product? (★★★)

In [71]:
A = np.random.randint(0,5,(5,5))
print("Matrix A:\n", A)
B = np.random.randint(0,5,(5,5))
print("Matrix B:\n", B)
print("Dot product matrix:\n", np.dot(A,B))
print("Diagonal of the dot product matrix:\n", np.diag(np.dot(A,B)))

Matrix A:
 [[2 3 4 0 1]
 [3 2 3 3 1]
 [4 3 2 3 0]
 [0 1 3 2 2]
 [2 3 4 3 4]]
Matrix B:
 [[1 2 0 2 2]
 [2 0 1 1 3]
 [1 1 0 2 2]
 [2 3 0 1 2]
 [1 1 0 4 0]]
Dot product matrix:
 [[13  9  3 19 21]
 [17 19  2 21 24]
 [18 19  3 18 27]
 [11 11  1 17 13]
 [22 21  3 34 27]]
Diagonal of the dot product matrix:
 [13 19  3 17 27]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [72]:
numpy_array = np.array([1,2,3,4,5])

In [73]:
interpolate_numpy_array = np.zeros(numpy_array.shape[0] + 3*(numpy_array.shape[0] - 1))
interpolate_numpy_array[::3+1] = numpy_array
interpolate_numpy_array

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [74]:
numpy_array_1 = np.random.randint(0,5, size=(5,5,3))
print(numpy_array_1.shape)
numpy_array_2 = np.random.randint(0,5, size=(5,5))
print(numpy_array_2.shape)
numpy_array_2 = np.expand_dims(numpy_array_2, axis=(numpy_array_2.ndim))
print(numpy_array_2.shape)
print(np.multiply(numpy_array_1, numpy_array_2)) # element-wise multiplication

(5, 5, 3)
(5, 5)
(5, 5, 1)
[[[ 0  0  0]
  [ 0  2  8]
  [ 0  2  1]
  [ 8  0  8]
  [ 0  0  0]]

 [[ 4  8  4]
  [ 6  0 12]
  [ 2  6  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 8 16  8]
  [ 0  6  4]
  [ 4  0  8]
  [ 6  2  2]
  [12  4  4]]

 [[12  6  9]
  [ 0  0  0]
  [ 3  3  3]
  [ 6  6  3]
  [ 6  0  6]]

 [[ 0 12  9]
  [ 0  0  0]
  [ 0  4  4]
  [ 3  0  2]
  [ 2  6  8]]]


#### 72. How to swap two rows of an array? (★★★)

In [75]:
numpy_array = np.random.randint(0,5, size=(5,5))
print(numpy_array)
numpy_array[[2,3],] = numpy_array[[3,2],]
print("Rows swapping:\n", numpy_array)
numpy_array[:,[2,3]] = numpy_array[:,[3,2]]
print("Column swapping:\n", numpy_array)

[[1 2 2 4 0]
 [1 1 0 4 0]
 [4 2 4 1 0]
 [2 3 4 4 0]
 [3 2 4 4 2]]
Rows swapping:
 [[1 2 2 4 0]
 [1 1 0 4 0]
 [2 3 4 4 0]
 [4 2 4 1 0]
 [3 2 4 4 2]]
Column swapping:
 [[1 2 4 2 0]
 [1 1 4 0 0]
 [2 3 4 4 0]
 [4 2 1 4 0]
 [3 2 4 4 2]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [76]:
# Question not clear

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [77]:
numpy_array = np.random.randint(0, 30, size = np.random.randint(10)) # some random array
print(numpy_array)
C = np.bincount(numpy_array) # calculating the count of occuracnce of above created array
print(C)
A = np.repeat(np.arange(len(C)), C) # By the length of  array C, creating an array starting from zero till the length of an array, then repeating the elements similar to C
print(A)
print("np.bincount(A): ", np.bincount(A))

[28 29 23]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1]
[23 28 29]
np.bincount(A):  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [78]:
numpy_array = np.random.randint(0, 10, size = 10) # some random array
print(numpy_array)
values_over_average = int(input("Enter the value over which average need to be taken (less than 10):"))
sliced_array = np.lib.stride_tricks.sliding_window_view(numpy_array, values_over_average)
print(sliced_array)
averages_array = np.array([])
for arr in sliced_array:
    averages_array = np.append(averages_array, np.mean(arr))
print(averages_array)

[2 3 4 5 8 3 9 3 6 0]


Enter the value over which average need to be taken (less than 10): 4


[[2 3 4 5]
 [3 4 5 8]
 [4 5 8 3]
 [5 8 3 9]
 [8 3 9 3]
 [3 9 3 6]
 [9 3 6 0]]
[3.5  5.   5.   6.25 5.75 5.25 4.5 ]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [79]:
Z = np.random.randint(0, 10, size = 10) # some random array
print(Z)
sliced_Z = np.lib.stride_tricks.sliding_window_view(Z, 3)
print(sliced_Z)

[4 5 9 5 9 0 6 0 5 2]
[[4 5 9]
 [5 9 5]
 [9 5 9]
 [5 9 0]
 [9 0 6]
 [0 6 0]
 [6 0 5]
 [0 5 2]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [80]:
p = 0.5
bool_array = np.random.choice(a=[False, True], size=(10), p=[p, 1-p]) # generate False, True with probabilities p and 1-p respectively, of size 10.
print(bool_array)
negated_bool_array = ~bool_array # negate the above boolean array
print(negated_bool_array)
print(np.logical_not(bool_array))
print(np.invert(bool_array))

float_array = np.random.random(10)
print(float_array)
print(np.negative(float_array))

[False False False False  True  True  True False  True False]
[ True  True  True  True False False False  True False  True]
[ True  True  True  True False False False  True False  True]
[ True  True  True  True False False False  True False  True]
[0.46403749 0.29318217 0.29315189 0.47255213 0.95891672 0.52215655
 0.89239466 0.89319254 0.00316884 0.81568405]
[-0.46403749 -0.29318217 -0.29315189 -0.47255213 -0.95891672 -0.52215655
 -0.89239466 -0.89319254 -0.00316884 -0.81568405]


In [81]:
# https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_hints_with_solutions.md
Z = np.random.randint(0,2,10)
print(Z)
print(np.logical_not(Z, out=Z))

Z = np.random.uniform(-1.0,1.0,10)
print(Z)
print(np.negative(Z, out=Z))

[1 1 0 0 0 0 1 1 0 0]
[0 0 1 1 1 1 0 0 1 1]
[-0.71697338 -0.41227681  0.32403297 -0.74795982 -0.13212122  0.67256269
  0.08649516 -0.93308692 -0.92665414 -0.9628005 ]
[ 0.71697338  0.41227681 -0.32403297  0.74795982  0.13212122 -0.67256269
 -0.08649516  0.93308692  0.92665414  0.9628005 ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [82]:
# distance reference: https://stackoverflow.com/questions/39840030/distance-between-point-and-a-line-from-two-points
lines = np.random.randint(0,5, size=(2,2,2))
#lines = np.array([[[1,7],[3,4]]])
p = np.random.randint(0,5, size=(2))
#p = np.array([2,9])
for line in lines:
    distance = np.linalg.norm(np.cross(line[1]-line[0], line[0]-p))/np.linalg.norm(line[1]-line[0])
    print("The distance of point", p, "from line joining points", line, "is", distance)

The distance of point [4 2] from line joining points [[3 0]
 [4 2]] is 0.0
The distance of point [4 2] from line joining points [[3 1]
 [0 3]] is 1.386750490563073


In [83]:
line = np.array([[[1,7],[3,4]]])
p = np.array([2,9])
slope = (lines[0][1][1] - lines[0][0][1])/(lines[0][1][0] - lines[0][0][0])
intercept = lines[0][1][1] - slope*lines[0][1][0]
slope_1 = -1/slope
intercept_1 = p[1] - slope_1*p[0]
x = (intercept - intercept_1)/(slope_1 - slope)
y = slope_1*x + intercept_1
distance = np.sqrt((p[1]-y)**2 + (p[0]-x)**2)
distance

4.919349550499538

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [84]:
lines = np.random.randint(0,5, size=(2,2,2))
P = np.random.randint(0,5, size=(3,2))
for line in lines:
    if (line[1] == line[0]).all():
        print("Both point are equal not a line:", line)
    else:
        for point in P:
            distance = np.linalg.norm(np.cross(line[1]-line[0], line[0]-point))/np.linalg.norm(line[1]-line[0])
            print("The distance of point", point, "from line joining points", line, "is", distance)

The distance of point [2 4] from line joining points [[0 1]
 [2 0]] is 3.5777087639996634
The distance of point [1 2] from line joining points [[0 1]
 [2 0]] is 1.3416407864998738
The distance of point [4 2] from line joining points [[0 1]
 [2 0]] is 2.6832815729997477
The distance of point [2 4] from line joining points [[4 3]
 [1 2]] is 1.5811388300841895
The distance of point [1 2] from line joining points [[4 3]
 [1 2]] is 0.0
The distance of point [4 2] from line joining points [[4 3]
 [1 2]] is 0.9486832980505138


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [85]:
def extract_and_center(numpy_array, pad_with):
    a = np.random.randint(1,len(numpy_array))
    b = np.random.randint(1,len(numpy_array))
    if a>b:
        dummy = a
        a = b
        b = dummy
    elif a == b:
        a -= 1
    
    extract = numpy_array[a:b+1]
    print("start index:", a, ", end index:", b)
    print("Extracted array", extract)
    new_array = np.pad(extract, (a, len(numpy_array) - b -1), 'constant', constant_values=0)
    return new_array

numpy_array = np.random.randint(0,5, size=(10))
print("Original array", numpy_array)
pad_with = int(input("With what value to be padded:"))
final_array = extract_and_center(numpy_array, pad_with)
print("Final array", final_array)

Original array [3 1 0 2 2 3 1 0 0 3]


With what value to be padded: 0


start index: 2 , end index: 5
Extracted array [0 2 2 3]
Final array [0 0 0 2 2 3 0 0 0 0]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [86]:
Z = np.arange(1,15,1)
print(Z)
R = np.lib.stride_tricks.sliding_window_view(Z, 4)
print(R)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [87]:
matrix = np.random.randint(0,5, size=(5,5))
rank = np.linalg.matrix_rank(matrix)
print("The matrix\n", matrix, "have rank:", rank)

The matrix
 [[2 3 2 2 3]
 [3 1 0 0 3]
 [0 1 1 4 3]
 [0 1 1 3 3]
 [3 2 3 2 1]] have rank: 5


#### 83. How to find the most frequent value in an array?

In [88]:
Z = np.random.randint(0,10,10)
print(Z)
most_occured_value = np.bincount(Z).argmax()
print(most_occured_value)

[9 7 6 6 0 3 7 9 7 8]
7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [89]:
# Step size = 1
matrix = np.random.randint(0,5, size=(10,10))
print(matrix)
R = np.lib.stride_tricks.sliding_window_view(matrix, (3,3))
print(R)

[[4 1 3 2 1 0 3 3 3 1]
 [1 1 4 1 0 0 0 4 0 1]
 [2 4 4 0 0 2 0 4 3 1]
 [4 1 4 0 4 0 2 2 0 3]
 [2 4 2 0 4 0 4 2 1 0]
 [3 3 1 4 2 4 4 2 0 2]
 [1 0 3 4 3 3 4 1 3 2]
 [2 0 3 0 4 0 4 1 2 3]
 [2 2 1 2 4 1 4 1 3 3]
 [3 4 3 3 3 4 0 0 4 2]]
[[[[4 1 3]
   [1 1 4]
   [2 4 4]]

  [[1 3 2]
   [1 4 1]
   [4 4 0]]

  [[3 2 1]
   [4 1 0]
   [4 0 0]]

  [[2 1 0]
   [1 0 0]
   [0 0 2]]

  [[1 0 3]
   [0 0 0]
   [0 2 0]]

  [[0 3 3]
   [0 0 4]
   [2 0 4]]

  [[3 3 3]
   [0 4 0]
   [0 4 3]]

  [[3 3 1]
   [4 0 1]
   [4 3 1]]]


 [[[1 1 4]
   [2 4 4]
   [4 1 4]]

  [[1 4 1]
   [4 4 0]
   [1 4 0]]

  [[4 1 0]
   [4 0 0]
   [4 0 4]]

  [[1 0 0]
   [0 0 2]
   [0 4 0]]

  [[0 0 0]
   [0 2 0]
   [4 0 2]]

  [[0 0 4]
   [2 0 4]
   [0 2 2]]

  [[0 4 0]
   [0 4 3]
   [2 2 0]]

  [[4 0 1]
   [4 3 1]
   [2 0 3]]]


 [[[2 4 4]
   [4 1 4]
   [2 4 2]]

  [[4 4 0]
   [1 4 0]
   [4 2 0]]

  [[4 0 0]
   [4 0 4]
   [2 0 4]]

  [[0 0 2]
   [0 4 0]
   [0 4 0]]

  [[0 2 0]
   [4 0 2]
   [4 0 4]]

  [[2 0 4]
   [0 2 2]
   [0 4 

In [90]:
# Step size = 3
matrix = np.random.randint(0,5, size=(10,10))
print(matrix)
R = np.lib.stride_tricks.sliding_window_view(matrix, (3,3))[::3,::3]
print(R)

[[2 0 4 0 3 3 3 1 4 4]
 [4 2 1 3 3 1 0 3 1 3]
 [4 1 4 0 1 1 2 2 3 0]
 [2 2 1 2 0 4 0 1 1 0]
 [2 4 0 4 1 1 4 3 1 4]
 [2 2 2 4 4 3 0 2 1 2]
 [0 0 4 3 4 1 2 3 2 1]
 [3 3 3 4 0 4 0 4 0 0]
 [1 0 2 1 4 3 1 3 1 2]
 [4 1 1 1 3 4 3 2 0 4]]
[[[[2 0 4]
   [4 2 1]
   [4 1 4]]

  [[0 3 3]
   [3 3 1]
   [0 1 1]]

  [[3 1 4]
   [0 3 1]
   [2 2 3]]]


 [[[2 2 1]
   [2 4 0]
   [2 2 2]]

  [[2 0 4]
   [4 1 1]
   [4 4 3]]

  [[0 1 1]
   [4 3 1]
   [0 2 1]]]


 [[[0 0 4]
   [3 3 3]
   [1 0 2]]

  [[3 4 1]
   [4 0 4]
   [1 4 3]]

  [[2 3 2]
   [0 4 0]
   [1 3 1]]]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [91]:
matrix = np.random.randint(0,5, size=(10,10))
print("Original Matrix:\n", matrix)
R = np.lib.stride_tricks.sliding_window_view(matrix, len(matrix), 0)
print("Transpose:\n", R)

Original Matrix:
 [[2 3 0 0 2 3 0 3 4 3]
 [4 2 0 1 1 3 2 2 4 3]
 [4 1 3 1 0 1 4 1 2 0]
 [2 3 1 3 1 1 4 3 2 2]
 [0 1 4 3 1 3 2 3 3 4]
 [1 4 0 1 0 3 3 2 1 2]
 [3 3 4 2 0 3 1 0 2 4]
 [2 4 2 2 3 0 1 3 1 2]
 [4 3 1 2 1 0 4 1 0 2]
 [2 0 3 4 0 4 0 4 4 0]]
Transpose:
 [[[2 4 4 2 0 1 3 2 4 2]
  [3 2 1 3 1 4 3 4 3 0]
  [0 0 3 1 4 0 4 2 1 3]
  [0 1 1 3 3 1 2 2 2 4]
  [2 1 0 1 1 0 0 3 1 0]
  [3 3 1 1 3 3 3 0 0 4]
  [0 2 4 4 2 3 1 1 4 0]
  [3 2 1 3 3 2 0 3 1 4]
  [4 4 2 2 3 1 2 1 0 4]
  [3 3 0 2 4 2 4 2 2 0]]]


In [92]:
matrix = np.random.randint(0,5, size=(10,10))
print("Original Matrix:\n", matrix)
print("Transpose:\n", matrix.transpose())

Original Matrix:
 [[0 4 4 2 3 4 3 4 0 2]
 [4 1 1 4 3 0 0 4 2 3]
 [2 3 3 1 2 3 4 1 4 0]
 [1 4 0 3 4 0 2 0 4 1]
 [2 1 4 4 3 2 3 2 4 1]
 [2 4 0 1 1 2 4 1 2 4]
 [3 0 4 1 1 3 1 3 1 3]
 [0 0 1 2 0 4 2 4 4 2]
 [1 0 3 3 1 2 4 0 3 2]
 [4 0 4 0 4 3 4 2 0 2]]
Transpose:
 [[0 4 2 1 2 2 3 0 1 4]
 [4 1 3 4 1 4 0 0 0 0]
 [4 1 3 0 4 0 4 1 3 4]
 [2 4 1 3 4 1 1 2 3 0]
 [3 3 2 4 3 1 1 0 1 4]
 [4 0 3 0 2 2 3 4 2 3]
 [3 0 4 2 3 4 1 2 4 4]
 [4 4 1 0 2 1 3 4 0 2]
 [0 2 4 4 4 2 1 4 3 0]
 [2 3 0 1 1 4 3 2 2 2]]


#### 86. Consider a set of p matrices which has shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [93]:
matrix = np.random.randint(0,5, size=(3,3,3))
print("Set of matrices:\n", matrix)
vector = np.random.randint(0,5, size=(3,3,1))
print("Set of vectors:\n", vector)
print("Sum of of the matrix products:\n", (np.matmul(matrix, vector).sum(axis=0)))

Set of matrices:
 [[[4 1 2]
  [4 2 0]
  [3 4 3]]

 [[3 3 4]
  [0 2 3]
  [2 2 0]]

 [[3 1 0]
  [3 0 3]
  [3 1 3]]]
Set of vectors:
 [[[4]
  [0]
  [0]]

 [[0]
  [3]
  [2]]

 [[4]
  [1]
  [3]]]
Sum of of the matrix products:
 [[46]
 [49]
 [40]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [94]:
# Step size = 1
matrix = np.random.randint(0,5, size=(16,16))
print(matrix)
print("Enter two values, 1st value representing row block, 2nd value representing column block (both are of step size one):")
row_block = int(input())
column_block = int(input())
R = np.lib.stride_tricks.sliding_window_view(matrix, (4,4))
print(R[row_block][column_block])
print(np.sum(R[row_block][column_block]))

[[3 2 4 2 4 3 3 3 2 4 3 4 0 3 4 1]
 [2 2 1 0 3 3 2 4 3 2 3 1 2 3 1 1]
 [0 2 3 3 0 3 3 2 4 0 1 1 3 3 4 4]
 [0 2 3 2 1 2 0 3 3 4 4 0 2 2 2 1]
 [3 1 0 0 4 0 2 2 1 0 3 0 2 0 1 4]
 [3 1 4 4 1 3 2 1 2 4 3 3 3 1 2 1]
 [4 0 3 0 3 4 2 2 2 2 0 2 3 1 4 0]
 [0 3 0 2 2 0 1 0 2 3 0 1 1 1 3 0]
 [4 0 3 0 2 4 1 3 3 2 1 4 4 4 3 0]
 [0 1 2 4 4 2 4 0 2 2 0 4 3 2 3 4]
 [2 2 1 2 4 3 3 1 4 4 0 3 3 0 4 3]
 [0 2 4 3 4 0 3 0 2 2 1 1 1 4 4 1]
 [0 0 1 2 4 0 2 4 0 0 3 1 4 1 2 1]
 [1 1 0 4 4 4 0 4 4 3 4 0 3 3 4 4]
 [0 4 2 1 2 1 1 2 0 4 2 0 0 4 4 3]
 [2 2 2 4 0 1 1 0 2 0 2 4 1 1 4 2]]
Enter two values, 1st value representing row block, 2nd value representing column block (both are of step size one):


 5
 0


[[3 1 4 4]
 [4 0 3 0]
 [0 3 0 2]
 [4 0 3 0]]
31


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [95]:
'''
# Ref: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_hints_with_solutions.md
# Game of life question explanation: https://www.youtube.com/watch?v=ti6Ruupq2mg

four rules:
1. Any live cell with fewer than two live neighbors dies as if caused by under-population.
2. Any live cell with two or three live neighbors lives on to the next generation.
3. Any live cell with more than three live neighbors dies, as if by over-population.
4. Any dead cell with exactly three live neighbors becomes a live cell, as if by reproduction.
'''

present_state = np.random.randint(0,2,(10,10))
print("Present state:\n", present_state)
next_state = np.zeros(present_state.shape, dtype=np.int8)
for i in range(len(present_state)):
    for j in range(present_state.shape[-1]):
        if i==0 and j==0:
            dummy = present_state[i][j+1] + present_state[i+1][j] + present_state[i+1][j+1]
        elif i==0 and j!=(present_state.shape[-1]-1):
            dummy = present_state[i][j-1] + present_state[i+1][j-1] + present_state[i+1][j] + present_state[i+1][j+1] + present_state[i][j+1]
        elif i==0 and j==(present_state.shape[-1]-1):
            dummy = present_state[i][j-1] + present_state[i+1][j-1] + present_state[i+1][j]
        elif i!=(len(present_state)-1) and j==0:
            dummy = present_state[i-1][j] + present_state[i-1][j+1] + present_state[i][j+1] + present_state[i+1][j+1] + present_state[i+1][j]
        elif i!=(len(present_state)-1) and j==(present_state.shape[-1]-1):
            dummy = present_state[i-1][j-1] + present_state[i-1][j] + present_state[i][j-1] + present_state[i+1][j-1] + present_state[i+1][j]
        elif i==(len(present_state)-1) and j==0:
            dummy = present_state[i-1][j] + present_state[i-1][j+1] + present_state[i][j+1]
        elif i==(len(present_state)-1) and j!=(present_state.shape[-1]-1):
            dummy = present_state[i][j-1] + present_state[i-1][j-1] + present_state[i-1][j] + present_state[i-1][j+1] + present_state[i][j+1]
        elif i==(len(present_state)-1) and j==(present_state.shape[-1]-1):
            dummy = present_state[i][j-1] + present_state[i-1][j-1] + present_state[i-1][j]
        else:
            dummy = present_state[i-1][j-1] + present_state[i-1][j] + present_state[i-1][j+1] + present_state[i][j+1] + present_state[i+1][j+1] + present_state[i+1][j] + present_state[i+1][j-1] + present_state[i][j-1]
        
        if present_state[i][j] == 0:
            if dummy == 3:
                next_state[i][j] = 1
        elif present_state[i][j] == 1:
            if (dummy < 2) or (dummy > 4):
                next_state[i][j] = 0
            elif dummy == 2 or dummy == 3:
                next_state[i][j] = 1
print("Next state:\n", next_state)

Present state:
 [[0 1 1 1 1 0 1 0 1 0]
 [1 0 0 0 0 0 0 0 1 0]
 [1 0 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 1 0 0 1]
 [1 1 1 1 1 1 0 1 1 0]
 [1 1 0 0 0 1 1 0 0 1]
 [1 1 0 0 0 0 0 1 1 1]
 [1 0 0 0 1 1 0 1 0 1]
 [0 1 0 1 1 1 1 1 0 0]
 [1 1 0 0 1 0 1 1 1 1]]
Next state:
 [[0 1 1 1 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 1 0]
 [0 1 0 1 1 1 1 1 1 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 1 1 1 0 0 1 1 1]
 [0 0 0 1 0 1 0 0 0 1]
 [0 0 0 0 1 0 0 1 0 1]
 [1 0 1 1 0 0 0 0 0 1]
 [0 1 1 1 0 0 0 0 0 1]
 [1 1 1 1 1 0 0 0 1 0]]


In [96]:
dummy = 0
if (dummy < 2) or (dummy > 4):
    print("True")

True


In [97]:
np.set_printoptions(threshold=float('inf'))
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(10,10))
print(Z)
for i in range(100): Z = iterate(Z)
print(Z)

[[1 1 0 0 1 0 1 0 0 1]
 [1 1 0 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 0 0 0 0]
 [0 1 1 0 1 1 0 1 0 1]
 [0 0 1 0 0 0 1 0 1 1]
 [0 1 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 1 1 0 1 0]
 [0 0 1 1 0 1 0 0 0 1]
 [0 0 1 0 1 1 1 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [98]:
size_array = int(input("Enter the size of the array:"))
lower_bound = int(input("Enter the lowest value allowed in an array:"))
upper_bound = int(input("Enter the highest value allowed in an array:"))
n = int(input("How many largest values you want:"))
numpy_array = np.random.randint(lower_bound, upper_bound, size=size_array)
print(numpy_array)
numpy_array[::-1].sort()
print(numpy_array)
print(numpy_array[0:n])

Enter the size of the array: 20
Enter the lowest value allowed in an array: 0
Enter the highest value allowed in an array: 50
How many largest values you want: 5


[32 38  4  6 15  5 30 40 12 48 35 20 34 20 46 15  0  3 47 45]
[48 47 46 45 40 38 35 34 32 30 20 20 15 15 12  6  5  4  3  0]
[48 47 46 45 40]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [99]:
numpy_array = np.random.randint(0, 10, size=(2,3))
print(numpy_array)
result = np.transpose([np.tile(numpy_array[0], len(numpy_array[1])), np.repeat(numpy_array[1], len(numpy_array[0]))]) # np. repeat function repeats the individual elements of an input array. But np. tile will take the entire array
print(result)

[[2 9 6]
 [7 0 3]]
[[2 7]
 [9 7]
 [6 7]
 [2 0]
 [9 0]
 [6 0]
 [2 3]
 [9 3]
 [6 3]]


#### 91. How to create a record array from a regular array? (★★★)

In [100]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [101]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
r = np.core.records.fromarrays(Z.T, dtype=np.dtype([('col1', 'S8'), ('col2', 'f8'), ('col3', 'i8')]))
print(r)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [102]:
numpy_array = np.random.randint(0, 10, size=30)
print(numpy_array)
print(numpy_array**3)
print(np.power(numpy_array,3))
print(np.einsum('i,i,i->i',numpy_array,numpy_array,numpy_array))

[2 0 0 2 7 9 9 0 8 9 9 8 5 9 5 3 6 7 7 7 0 6 1 1 8 5 1 8 7 5]
[  8   0   0   8 343 729 729   0 512 729 729 512 125 729 125  27 216 343
 343 343   0 216   1   1 512 125   1 512 343 125]
[  8   0   0   8 343 729 729   0 512 729 729 512 125 729 125  27 216 343
 343 343   0 216   1   1 512 125   1 512 343 125]
[  8   0   0   8 343 729 729   0 512 729 729 512 125 729 125  27 216 343
 343 343   0 216   1   1 512 125   1 512 343 125]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [103]:
matrix_1 = np.random.randint(0,5, size=(8,3))
matrix_2 = np.random.randint(0,5, size=(2,2))
print(matrix_1)
print(matrix_2)
for arr in matrix_1:
    print(set(matrix_2.flatten()).issubset(set(arr)))

[[0 3 3]
 [2 0 0]
 [0 1 2]
 [3 4 4]
 [3 3 2]
 [3 1 0]
 [2 4 2]
 [4 0 1]]
[[3 2]
 [0 2]]
False
False
False
False
False
False
False
False


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [104]:
matrix = np.random.randint(0,5, size=(10,3))
print(matrix)
unequal_values_in_rows = np.array([], dtype = np.int32)
for vector in matrix:
    if np.all(vector == vector[0]) == False:
        unequal_values_in_rows = np.append(unequal_values_in_rows, vector)
print(unequal_values_in_rows.reshape(int(len(unequal_values_in_rows)/matrix.shape[1]), matrix.shape[1]))

[[2 1 1]
 [3 4 1]
 [3 0 2]
 [3 4 1]
 [4 0 1]
 [0 3 1]
 [0 2 4]
 [4 0 0]
 [4 1 3]
 [3 4 4]]
[[2 1 1]
 [3 4 1]
 [3 0 2]
 [3 4 1]
 [4 0 1]
 [0 3 1]
 [0 2 4]
 [4 0 0]
 [4 1 3]
 [3 4 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [105]:
numpy_array = np.random.randint(0, 7, size=10, dtype=np.uint8)
print(numpy_array)
b = np.unpackbits(numpy_array.reshape(-1,1), axis=1)
print(b)

[2 2 0 0 0 5 6 2 3 1]
[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [106]:
matrix = np.random.randint(0,5, size=(10,3))
print(matrix)
print(np.unique(matrix, axis=0))

[[4 1 3]
 [3 3 0]
 [1 0 4]
 [2 1 0]
 [1 4 4]
 [1 3 2]
 [4 4 1]
 [1 1 2]
 [2 0 4]
 [3 2 2]]
[[1 0 4]
 [1 1 2]
 [1 3 2]
 [1 4 4]
 [2 0 4]
 [2 1 0]
 [3 2 2]
 [3 3 0]
 [4 1 3]
 [4 4 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [107]:
A = np.random.randint(0, 50, size=10)
B = np.random.randint(0, 50, size=10)
print(A, B)

[23  9 37 49 45  7 21 19 42  5] [18 12 25 28 21  0 26 37 31 19]


In [108]:
print("inner ((A).(B.T))", np.einsum('i,i',A,B))
print("outer ((A.T).(B))", np.einsum('i,j',A,B))
print("sum:", np.einsum('i->', A))
print("multiplication:", np.einsum('i,i->i',A,B))

inner ((A).(B.T)) 6410
outer ((A.T).(B)) [[ 414  276  575  644  483    0  598  851  713  437]
 [ 162  108  225  252  189    0  234  333  279  171]
 [ 666  444  925 1036  777    0  962 1369 1147  703]
 [ 882  588 1225 1372 1029    0 1274 1813 1519  931]
 [ 810  540 1125 1260  945    0 1170 1665 1395  855]
 [ 126   84  175  196  147    0  182  259  217  133]
 [ 378  252  525  588  441    0  546  777  651  399]
 [ 342  228  475  532  399    0  494  703  589  361]
 [ 756  504 1050 1176  882    0 1092 1554 1302  798]
 [  90   60  125  140  105    0  130  185  155   95]]
sum: 257
multiplication: [ 414  108  925 1372  945    0  546  703 1302   95]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [109]:
def getEquidistantPoints(p1, p2, parts):
    return zip(np.linspace(p1[0], p2[0], parts+1), np.linspace(p1[1], p2[1], parts+1))

list(getEquidistantPoints((1,10), (6,5), 5))

[(1.0, 10.0), (2.0, 9.0), (3.0, 8.0), (4.0, 7.0), (5.0, 6.0), (6.0, 5.0)]

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [110]:
# ref: what is multinomial distribution, https://www.statisticshowto.com/multinomial-distribution/
n = 5
X = np.random.randint(0, 4, size=(5,4)) # 2D array can contain float, but I am taking only integer
print("X:\n", X, "\n rows with sum = ", n, "\n are ", X[np.sum(X, axis=X.ndim-1) == n])

X:
 [[2 1 0 3]
 [1 2 1 0]
 [0 0 2 1]
 [3 0 1 0]
 [2 1 1 3]] 
 rows with sum =  5 
 are  []


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [112]:
X = np.random.randn(100) # random array
print("Shape of X:", X.shape)
N = 1000 # number of bootstrap samples
indices = np.random.randint(0, X.size, (N, X.size)) # creating index array of shape (N, 100) with values ranging from 0 to 99.
print("Shape of indices:", indices.shape)
mean_samples = X[indices].mean(axis=1) # creating mean_sample array of size N. mean is calculated of elements after replacement of 100 elements given by idx array.
confint = np.percentile(mean_samples, [2.5, 97.5])
print("95% confidence intervals are; 2.5% boundary:", confint[0], "97.5% boundary:", confint[1])

Shape of X: (100,)
Shape of indices: (1000, 100)
95% confidence intervals are; 2.5% boundary: -0.21729811530327664 97.5% boundary: 0.1591576782738012


Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Share your solutions and help others on the forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561
- Check out our course on "Data Analysis with Python: Zero to Pandas" - https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/rougier/numpy-100